import Provider from '../components/Provider';
import './globals.css';

export const metadata = {
  title: 'Next CRUP app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
